/* GENERATED by scripts/build-shells.js — do not edit by hand.
   HSK 4 Grammar Lab — offline support.
   Everything is precached at install (all 27 topics work offline from the
   first visit); fetches are network-first with a short timeout so flaky
   connections fall back to cache instead of hanging. */
const CACHE = "hsk4lab-425b6d502a";
const PRECACHE = [
  "./",
  "index.html",
  "review.html",
  "404.html",
  "manifest.webmanifest",
  "assets/style.css",
  "assets/app.js",
  "assets/manifest.js",
  "assets/data/vocab.js",
  "assets/icon.svg",
  "assets/icon-192.png",
  "assets/icon-512.png",
  "assets/icon-maskable-512.png",
  "assets/apple-touch-icon.png",
  "topics/result-complements.html",
  "topics/directional-complements.html",
  "topics/potential-complements.html",
  "topics/degree-state-complements.html",
  "topics/duration-frequency.html",
  "topics/ba-sentences.html",
  "topics/passive-bei.html",
  "topics/comparisons.html",
  "topics/shi-de-emphasis.html",
  "topics/lian-dou.html",
  "topics/questions-indefinites.html",
  "topics/jiu-vs-cai.html",
  "topics/you-zai-hai.html",
  "topics/time-adverbs.html",
  "topics/attitude-adverbs.html",
  "topics/yue-lai-yue.html",
  "topics/cause-effect.html",
  "topics/conditionals.html",
  "topics/contrast-concession.html",
  "topics/addition-sequencing.html",
  "topics/de-particles.html",
  "topics/separable-verbs.html",
  "topics/zhe-reduplication.html",
  "topics/prepositions.html",
  "topics/numbers-approx.html",
  "topics/confusables.html",
  "topics/exam-practice.html",
  "assets/data/result-complements.js",
  "assets/data/directional-complements.js",
  "assets/data/potential-complements.js",
  "assets/data/degree-state-complements.js",
  "assets/data/duration-frequency.js",
  "assets/data/ba-sentences.js",
  "assets/data/passive-bei.js",
  "assets/data/comparisons.js",
  "assets/data/shi-de-emphasis.js",
  "assets/data/lian-dou.js",
  "assets/data/questions-indefinites.js",
  "assets/data/jiu-vs-cai.js",
  "assets/data/you-zai-hai.js",
  "assets/data/time-adverbs.js",
  "assets/data/attitude-adverbs.js",
  "assets/data/yue-lai-yue.js",
  "assets/data/cause-effect.js",
  "assets/data/conditionals.js",
  "assets/data/contrast-concession.js",
  "assets/data/addition-sequencing.js",
  "assets/data/de-particles.js",
  "assets/data/separable-verbs.js",
  "assets/data/zhe-reduplication.js",
  "assets/data/prepositions.js",
  "assets/data/numbers-approx.js",
  "assets/data/confusables.js",
  "assets/data/exam-practice.js"
];
const TIMEOUT_MS = 3500;

self.addEventListener("install", e => {
  e.waitUntil(
    caches.open(CACHE)
      // allSettled: one missing file must not sink the whole install
      .then(c => Promise.allSettled(PRECACHE.map(u => c.add(u))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  if (new URL(req.url).origin !== location.origin) return; // fonts etc: browser handles
  e.respondWith((async () => {
    const net = fetch(req).then(res => {
      if (res.status === 200) {
        const copy = res.clone();
        e.waitUntil(caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {}));
      }
      return res;
    });
    net.catch(() => {}); // handled below — avoid an unhandled rejection when the timeout wins
    try {
      return await Promise.race([
        net,
        new Promise((_, rej) => setTimeout(() => rej(new Error("timeout")), TIMEOUT_MS))
      ]);
    } catch (err) {
      const hit = await caches.match(req, { ignoreSearch: true });
      if (hit) return hit;
      try { return await net; } catch (e2) {} // nothing cached: give the network its full chance
      if (req.mode === "navigate") {
        const idx = await caches.match("index.html");
        if (idx) return idx;
      }
      return new Response("Offline — this page isn't cached yet.", { status: 503, headers: { "Content-Type": "text/plain" } });
    }
  })());
});
